### ISSUE TITLE
Mean of PASSWORD_FOR_EVENTS

### ISSUE THREAD

**Issue by ZamanOof** [taigaio/taiga-doc#209]
Hello,
at https://taigaio.github.io/taiga-doc/dist/setup-production.html of events config.json
what mean of PASSWORD_FOR_EVENTS?
Best Regards

**Comment by theriverman** [comment]
Hi,

In case you configure your Taiga instance with taiga-events (it's a separate module), you need to assign a RabbitMQ vhost for it. In the documentation the recommended parameters are the following:
  * vhost=taiga
  * user=taiga
  * password=`PASSWORD_FOR_EVENTS`

Where `PASSWORD_FOR_EVENTS` is a password defined by you for obvious security reasons.
It's used in multiple places through the settings so the value of `PASSWORD_FOR_EVENTS` must be exactly the same, otherwise, the backend will not be able to connect to the selected RabbitMQ vhost.
