### ISSUE TITLE
debian prod installation

### ISSUE THREAD

**Issue by HongPong** [taigaio/taiga-doc#45]
Hello, I am going to try and install this on debian. would you like a debian installer page pull req, if i can get it working? how should that be included in the repo, if so.

**Comment by jespino** [comment]
Sure, if you make a pull-request with instruction for install Taiga on debian, this will be accepted (after testing it, of course).

Are you thinking in debian stable, testing or sid? I say it because if you use testing or sid, the documentation can be obsolete earlier.

Take care with the dependencies, you need at least PostgreSQL 9.3 and Python 3.4.

The documentation must be based on the stable branch of Taiga.

**Comment by bameda** [comment]
Maybe this article might be useful for you https://github.com/taigaio/taiga-front/wiki/install-guides

**Comment by HongPong** [comment]
Thank you so much, I didn't spot that page earlier. The dependencies seem to be working using debian testing. Much appreciate the help!

**Comment by superalex** [comment]
This one was solved with https://github.com/taigaio/taiga-doc/commit/84f1ac3c410ecc32191b85c61ae062c36993563d :+1:
