### ISSUE TITLE
Incorrect IP/port instructions for production setup

### ISSUE THREAD

**Issue by agolden** [taigaio/taiga-doc#48]
The documentation says that in the '~/circus.ini' file, the following line should appear:

args = -w 3 -t 60 --pythonpath=. -b 127.0.0.1:8001 taiga.wsgi

Given that the documentation also states that the production server is to run on '80.88.23.45', and by default, Taiga expects the API server to run on port 8000, this line should read:

args = -w 3 -t 60 --pythonpath=. -b 80.88.23.45:8000 taiga.wsgi

**Comment by superalex** [comment]
We prefer not using 8000 port because it's the one "python manage runserver" needs by default. In a production environment "127.0.0.1:8001" is using only inside the server, the nginx is needs to proxy_pass it, we don't expose the back from circus directly so you don't need to use there the public IP.

**Comment by agolden** [comment]
OK, for some reason I'm not getting 8000 exposed on the public IP using the config shown in the documentation.  still investigating...
